/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Carolina
 */
public class FormularioReserva extends javax.swing.JInternalFrame{

    /**
     * Creates new form FormularioReserva1
     */
    public FormularioReserva() {
        initComponents();
        mostrar("");
        inhabilitar();
    }
    private String accion = "guardar";
    public static int idusuario;

    public void ocultar_columnas() {

        jTablelistreserva.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablelistreserva.getColumnModel().getColumn(0).setMinWidth(0);
        jTablelistreserva.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTablelistreserva.getColumnModel().getColumn(1).setMaxWidth(0);
        jTablelistreserva.getColumnModel().getColumn(1).setMinWidth(0);
        jTablelistreserva.getColumnModel().getColumn(1).setPreferredWidth(0);

        jTablelistreserva.getColumnModel().getColumn(3).setMaxWidth(0);
        jTablelistreserva.getColumnModel().getColumn(3).setMinWidth(0);
        jTablelistreserva.getColumnModel().getColumn(3).setPreferredWidth(0);

        jTablelistreserva.getColumnModel().getColumn(5).setMaxWidth(0);
        jTablelistreserva.getColumnModel().getColumn(5).setMinWidth(0);
        jTablelistreserva.getColumnModel().getColumn(5).setPreferredWidth(0);
        
        jTablelistreserva.getColumnModel().getColumn(6).setMaxWidth(0);
        jTablelistreserva.getColumnModel().getColumn(6).setMinWidth(0);
        jTablelistreserva.getColumnModel().getColumn(6).setPreferredWidth(0);
    }

    public void inhabilitar() {

        txtidreserva.setVisible(false);
        txtidhabitacion.setVisible(false);
        txtidcliente.setVisible(false);
        //txtidempleado.setVisible(false);

        txtnumero.setEnabled(false);
        txtcliente.setEnabled(false);
        //txtempleado.setEnabled(false);
        cbotipo_reserva.setEnabled(false);

        /*
        jDateChooserfecha_reserva.setEnabled(false);
        jDateChooserfecha_ingreso.setEnabled(false);
        jDateChooserfecha_salida.setEnabled(false);
         */
        txtprecio_alojamiento.setEnabled(false);
        cboestado_reserva.setEnabled(false);

        btnguardar.setEnabled(false);
        btncancelar.setEnabled(false);
        btneliminar.setEnabled(false);

        btnbuscarhabitacion.setEnabled(false);
        btnbuscarhabitacion.setEnabled(false);

        txtidreserva.setText("");
        txtidcliente.setText("");
        txtnumero.setText("");
        txtcliente.setText("");
        txtprecio_alojamiento.setText("");
        txtidhabitacion.setText("");

    }

    public void habilitar() {

        txtidreserva.setVisible(false);
        txtidhabitacion.setVisible(false);
        txtidcliente.setVisible(false);
       // txtidempleado.setVisible(false);

        txtnumero.setEnabled(false);
        txtcliente.setEnabled(false);
        //txtempleado.setEnabled(false);

        cbotipo_reserva.setEnabled(true);

        /*
        jDateChooserfecha_reserva.setEnabled(true);
        jDateChooserfecha_ingreso.setEnabled(true);
        jDateChooserfecha_salida.setEnabled(true);
         */
        txtprecio_alojamiento.setEnabled(true);
        cboestado_reserva.setEnabled(true);

        btnguardar.setEnabled(true);
        btncancelar.setEnabled(true);
        btneliminar.setEnabled(true);

        btnbuscarhabitacion.setEnabled(true);
        btnbuscarhabitacion.setEnabled(true);

        txtidreserva.setText("");
        txtidcliente.setText("");
        txtnumero.setText("");
        txtcliente.setText("");
        txtprecio_alojamiento.setText("");
        txtidhabitacion.setText("");

    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            CRUDReserva func = new CRUDReserva();
            modelo = func.mostrar(buscar);

            jTablelistreserva.setModel(modelo);
            ocultar_columnas();
            lbltotalregistros.setText("Total Registros " + Integer.toString(func.totalregistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelhabitacion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablelistreserva = new javax.swing.JTable();
        jLabelbuscar1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lbltotalregistros = new javax.swing.JLabel();
        btnrealizarpagos = new javax.swing.JButton();
        btnconsumos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidreserva = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidhabitacion = new javax.swing.JTextField();
        btnbuscarhabitacion = new javax.swing.JButton();
        txtidcliente = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        btnbuscarcliente = new javax.swing.JButton();
        cboestado_reserva = new javax.swing.JComboBox<>();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbotipo_reserva = new javax.swing.JComboBox<>();
        txtprecio_alojamiento = new javax.swing.JTextField();
        dcfecha_salida = new com.toedter.calendar.JDateChooser();
        dcfecha_reserva = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        dcfecha_ingreso = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 79, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelhabitacion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelhabitacion.setText("Reserva");
        jPanel1.add(jLabelhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 110, -1));

        jPanel5.setBackground(new java.awt.Color(255, 239, 213));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Reserva"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablelistreserva.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jTablelistreserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablelistreserva.setToolTipText("");
        jTablelistreserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablelistreservaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTablelistreserva);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 520, 330));

        jLabelbuscar1.setText("Buscar");
        jPanel5.add(jLabelbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel5.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, -1));

        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel5.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsalir.setText("salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel5.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        lbltotalregistros.setForeground(new java.awt.Color(102, 102, 102));
        lbltotalregistros.setText("Registros");
        jPanel5.add(lbltotalregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 130, -1));

        btnrealizarpagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnrealizarpagos.setText("Realizar pagos");
        btnrealizarpagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrealizarpagosActionPerformed(evt);
            }
        });
        jPanel5.add(btnrealizarpagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        btnconsumos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnconsumos.setText("Consumos");
        btnconsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsumosActionPerformed(evt);
            }
        });
        jPanel5.add(btnconsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 540, 490));

        jPanel6.setBackground(new java.awt.Color(255, 239, 213));
        jPanel6.setForeground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registro de Reserva", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Habitación");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 140, -1));

        jLabel4.setText("Cliente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setText("Tipo de Reserva");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setText("Estado de Reserva");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setText("Fecha de reserva");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel2.add(txtidreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, -1));

        jLabel9.setText("Fecha de Ingreso");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel10.setText("Precio de alojamiento");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel2.add(txtidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 50, -1));

        btnbuscarhabitacion.setText("...");
        btnbuscarhabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarhabitacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscarhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 50, -1));
        jPanel2.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 50, -1));
        jPanel2.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 140, -1));

        btnbuscarcliente.setText("...");
        btnbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarclienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 50, -1));

        cboestado_reserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagado", "Reservado", "Anulado" }));
        cboestado_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboestado_reservaActionPerformed(evt);
            }
        });
        jPanel2.add(cboestado_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 170, -1));

        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel11.setText("Trabajador");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cbotipo_reserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reserva", "Alquilado" }));
        jPanel2.add(cbotipo_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, -1));

        txtprecio_alojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio_alojamientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtprecio_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, -1));
        jPanel2.add(dcfecha_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, -1));
        jPanel2.add(dcfecha_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel12.setText("Fecha de salida");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        jPanel2.add(dcfecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 460));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (!txtidreserva.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de Eliminar la Reserva?", "Confirmar", 2);

            if (confirmacion == 0) {
                CRUDReserva func = new CRUDReserva();
                DReserva dts = new DReserva();

                dts.setIdreserva(Integer.parseInt(txtidreserva.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (txtidhabitacion.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes Seleccionar una Habitación");
            txtidhabitacion.requestFocus();
            return;
        }
        if (txtidcliente.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes Seleccionar un Cliente");
            txtidcliente.requestFocus();
            return;
        }

        if (txtprecio_alojamiento.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un precio del Alojamiento");
            txtprecio_alojamiento.requestFocus();
            return;
        }

        DReserva dts = new DReserva();
        CRUDReserva func = new CRUDReserva();

        //enviar datos a toda mi tabla de reserva
        dts.setIdhabitacion(Integer.parseInt(txtidhabitacion.getText()));
        dts.setIdcliente(Integer.parseInt(txtidcliente.getText()));
        dts.setIdempleado(idusuario);

        int seleccionado = cbotipo_reserva.getSelectedIndex();
        dts.setTipo_reserva((String) cbotipo_reserva.getItemAt(seleccionado));

        // declarar tipo de datos calendar
        Calendar cal;
        int d, m, a;

        cal = dcfecha_reserva.getCalendar();

        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;//restarle para obtener un formato correcto
        dts.setFecha_reserva(new Date(a, m, d));

        cal = dcfecha_salida.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        dts.setFecha_ingreso(new Date(a, m, d));

        cal = dcfecha_salida.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        dts.setFecha_salida(new Date(a, m, d));

        dts.setCosto_alojamiento(Double.parseDouble(txtprecio_alojamiento.getText()));
        seleccionado = cboestado_reserva.getSelectedIndex();
        dts.setEstado((String) cboestado_reserva.getItemAt(seleccionado));
         
        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(null, "La reserva fue registrada satisfactoriamente");
                mostrar("");
                inhabilitar();

                //ocupamos la Habitación alquilada
                CRUDHabitacion func3 = new CRUDHabitacion();
                DHabitacion dts3 = new DHabitacion();
                dts3.setIdhabitacion(Integer.parseInt(txtidhabitacion.getText()));
                func3.ocupar(dts3);
            }

        } else if (accion.equals("editar")) {
            dts.setIdreserva(Integer.parseInt(txtidreserva.getText()));
           // dts.setIdempleado(Integer.parseInt(txtidempleado.getText()));//que trabajador está modificando los datos de la reserva
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "La reserva fue Editada satisfactoriamente");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jTablelistreservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablelistreservaMouseClicked

        btnguardar.setText("Editar");
        habilitar();
        btneliminar.setEnabled(true);
        accion = "editar";

        int fila = jTablelistreserva.rowAtPoint(evt.getPoint());

        txtidreserva.setText(jTablelistreserva.getValueAt(fila, 0).toString());
        txtidhabitacion.setText(jTablelistreserva.getValueAt(fila, 1).toString());
        txtnumero.setText(jTablelistreserva.getValueAt(fila, 2).toString());
        txtidcliente.setText(jTablelistreserva.getValueAt(fila, 3).toString());
        txtcliente.setText(jTablelistreserva.getValueAt(fila, 4).toString());
       // txtidempleado.setText(jTablelistreserva.getValueAt(fila, 5).toString());
        //txtempleado.setText(jTablelistreserva.getValueAt(fila, 6).toString());

        cbotipo_reserva.setSelectedItem(jTablelistreserva.getValueAt(fila, 7).toString());
      /*
        dcfecha_reserva.setDate(Date.valueOf(jTablelistreserva.getValueAt(fila, 8).toString()));
        dcfecha_ingreso.setDate(Date.valueOf(jTablelistreserva.getValueAt(fila, 9).toString()));
        dcfecha_salida.setDate(Date.valueOf(jTablelistreserva.getValueAt(fila, 10).toString()));*/
        
        txtprecio_alojamiento.setText(jTablelistreserva.getValueAt(fila, 11).toString());
        cboestado_reserva.setSelectedItem(jTablelistreserva.getValueAt(fila, 12).toString());
    }//GEN-LAST:event_jTablelistreservaMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        habilitar();
        btnguardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnconsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsumosActionPerformed

        int fila = jTablelistreserva.getSelectedRow();
        FormularioConsumo.idreserva= jTablelistreserva.getValueAt(fila, 0).toString();
        FormularioConsumo.cliente=jTablelistreserva.getValueAt(fila, 4).toString();
        FormularioConsumo form = new FormularioConsumo();
        InicioRestringido.escritorioRestringido.add(form);//formulario dentro de inicio
         form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btnconsumosActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnrealizarpagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrealizarpagosActionPerformed
        int fila = jTablelistreserva.getSelectedRow(); //seleccionar fila

        FormularioPago.idreserva = jTablelistreserva.getValueAt(fila, 0).toString();
        FormularioPago.cliente = jTablelistreserva.getValueAt(fila, 4).toString();
        FormularioPago.totalreserva =Double.parseDouble( jTablelistreserva.getValueAt(fila, 11).toString());
        FormularioPago.idhabitacion = jTablelistreserva.getValueAt(fila, 1).toString();
        FormularioPago.habitacion =jTablelistreserva.getValueAt(fila, 2).toString();
        FormularioPago form = new FormularioPago();
        InicioRestringido.escritorioRestringido.add(form);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btnrealizarpagosActionPerformed

    private void cboestado_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboestado_reservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboestado_reservaActionPerformed

    private void btnbuscarhabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarhabitacionActionPerformed
           try {
            FormularioVistaHabitacion form = new FormularioVistaHabitacion();
            InicioRestringido.escritorioRestringido.add(form);
            form.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscarhabitacionActionPerformed

    private void btnbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarclienteActionPerformed
             try {
            FormularioVistaCliente form = new FormularioVistaCliente();
            InicioRestringido.escritorioRestringido.add(form);
            form.setVisible(true);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscarclienteActionPerformed

    private void txtprecio_alojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio_alojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio_alojamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscarcliente;
    private javax.swing.JButton btnbuscarhabitacion;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsumos;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnrealizarpagos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cboestado_reserva;
    private javax.swing.JComboBox<String> cbotipo_reserva;
    private com.toedter.calendar.JDateChooser dcfecha_ingreso;
    private com.toedter.calendar.JDateChooser dcfecha_reserva;
    private com.toedter.calendar.JDateChooser dcfecha_salida;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelbuscar1;
    private javax.swing.JLabel jLabelhabitacion;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablelistreserva;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JTextField txtbuscar;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JTextField txtidcliente;
    public static javax.swing.JTextField txtidhabitacion;
    private javax.swing.JTextField txtidreserva;
    public static javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtprecio_alojamiento;
    // End of variables declaration//GEN-END:variables
}
